name: golangci-lint
on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
  pull_request:
    paths-ignore:
      - '*.md'
jobs:
  golangci:
    strategy:
      matrix:
        go-version: ["1.16.x","1.17.x"]
        os: [windows-latest, macos-latest, ubuntu-latest]
    name: golangci-lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        # https://golangci-lint.run/usage/linters/
        with:
          version: v1.43.0
          args: --verbose --disable-all -E misspell #-E errcheck -E revive -E gocritic -E goimports 